import { Fragment, useMemo, useState } from 'react';
import type { LedgerLensData } from '../domain/ledger';

export function LedgerLensScreen({ data, onBack }: { data: LedgerLensData; onBack: () => void }) {
  const [filter, setFilter] = useState('All');
  const [selected, setSelected] = useState<string | null>(null);
  const [copied, setCopied] = useState('');
  const entries = useMemo(() => data.entries.filter((entry) => filter === 'All' || filter === 'Matches' && entry.type === 'Match' || filter === 'Job state' && entry.type === 'Job' || filter === 'References' && entry.type !== 'Job' && entry.type !== 'Match'), [data, filter]);
  const copy = async (reference: string) => {
    await navigator.clipboard?.writeText(reference);
    setCopied(reference);
    setTimeout(() => setCopied(''), 1200);
  };

  return <main className="ledger-page"><header className="ledger-header"><span className="demo-flow-badge">Demo data</span><p>Ledger Lens</p><h1>See what becomes public — and what stays private.</h1><strong>AI Engineering Intern · Nova Labs</strong><small>Visual preview — real public state will later come from the Midnight provider/indexer.</small></header><section className="ledger-layout"><section className="ledger-main"><div className="ledger-toolbar"><div><span>Public state</span><h2>Only the minimum public record.</h2></div><div role="tablist" aria-label="Ledger filters">{['All', 'Job state', 'Matches', 'References'].map((item) => <button role="tab" aria-selected={filter === item} className={filter === item ? 'ledger-filter active' : 'ledger-filter'} onClick={() => setFilter(item)} key={item}>{item}</button>)}</div></div><div className="ledger-table-wrap"><table><caption>Demo public state and events</caption><thead><tr><th>Type</th><th>Reference</th><th>Visibility</th><th>Status</th><th>Action</th></tr></thead><tbody>{entries.map((entry) => <Fragment key={entry.id}><tr className={selected === entry.id ? 'selected' : ''}><td data-label="Type">{entry.type}</td><td data-label="Reference"><button className="entry-button" onClick={() => setSelected(selected === entry.id ? null : entry.id)}>{entry.reference}</button></td><td data-label="Visibility"><span className="public-tag">Public</span></td><td data-label="Status">{entry.status}</td><td data-label="Action"><button className="copy-button" onClick={() => copy(entry.reference)}>{copied === entry.reference ? 'Copied' : 'Copy'}</button></td></tr>{selected === entry.id && <tr className="ledger-detail"><td data-label="Public detail" colSpan={5}>{entry.summary}</td></tr>}</Fragment>)}</tbody></table></div><p className="copy-feedback" aria-live="polite">{copied ? `Copied demo reference ${copied}` : ''}</p></section><aside className="ledger-side"><section><span>Public summary</span><p>Job status <b>Open</b></p><p>Verified matches <b>{data.verifiedMatches}</b></p><p>Required availability <b>{data.requiredAvailability}</b></p><p>Contract <b>Demo reference</b></p></section><section><span>Public / on ledger</span><p>✓ Job ID and state</p><p>✓ Match count and successful references</p><p>✓ Uniqueness and contract references</p><small>Only the minimum public state needed for a valid match is represented here.</small></section><section className="not-ledger"><span>Private / not on ledger</span><p>⌾ Candidate minimum compensation</p><p>⌾ Candidate weekly availability</p><p>⌾ Candidate secret</p><small>These values are not part of the public match record.</small></section><section><span>Failed checks</span><p>An incompatible attempt does not appear as a successful public match.</p><b>Not published as a match</b></section><button className="secondary-action" onClick={onBack}>Back to recruiter</button></aside></section></main>;
}
