import { PillButton } from '../components/PillButton';
import { novaLabsJob } from '../demo-data/nova-labs-job';
import type { RecruiterDashboardData } from '../domain/recruiter';

export interface RecruiterDashboardProps {
  data: RecruiterDashboardData;
  onViewMatch: () => void;
  onOpenLedgerLens: () => void;
}

export function RecruiterDashboardScreen({ data, onViewMatch, onOpenLedgerLens }: RecruiterDashboardProps) {
  return <main className="recruiter-page"><header className="recruiter-header"><span className="demo-flow-badge">Demo data</span><p>Recruiter view</p><h1>{novaLabsJob.title}</h1><strong>{novaLabsJob.company}</strong><small>{novaLabsJob.location} · {novaLabsJob.mode} · <b>Open</b></small><em>Visual preview — public job and match data will later come from the Midnight integration.</em></header><section className="recruiter-metrics" aria-label="Job metrics"><article className="metric-main"><span>Verified matches</span><strong>{data.matchCount}</strong><p>Compatible tickets only</p></article><article><span>Required availability</span><strong>{data.requiredAvailability}</strong></article><article><span>Suggested compensation</span><strong>{data.suggestedCompensation}</strong></article></section><section className="recruiter-grid"><section className="verified-matches"><div className="section-title"><div><span>Verified matches</span><h2>Compatible, without private terms.</h2></div></div><div className="match-grid">{data.matches.map((match) => <article className="recruiter-match" key={match.reference}><span>Match #{match.reference}</span><p>✓ Compensation compatible</p><p>✓ Availability compatible</p><p>✓ Unique match for this job</p><div><small>Exact compensation <b>Not received</b></small><small>Exact availability <b>Not received</b></small></div><button type="button" onClick={onViewMatch}>View Match Pass →</button></article>)}</div></section><aside className="recruiter-side"><section className="dashboard-privacy"><span>Privacy receipt</span><p>ProofMatch verifies compatibility without giving the recruiter the candidate's exact private terms.</p><strong>Recruiter received</strong><small>✓ compatibility result<br />✓ match reference / ticket</small><strong>Recruiter did not receive</strong><small>⌾ exact minimum compensation<br />⌾ exact weekly availability<br />⌾ candidate secret</small></section><section className="public-summary"><span>Public match summary</span><p>Job <b>PM-AI-001</b></p><p>Job status <b>Open</b></p><p>Verified matches <b>{data.matchCount}</b></p><p>Failed attempts <b>Not published</b></p></section><section className="ledger-cta"><span>Ledger Lens</span><p>See exactly what is public and what stayed private.</p><PillButton onClick={onOpenLedgerLens}>Open Ledger Lens <span aria-hidden="true">→</span></PillButton></section></aside></section></main>;
}
